name: gitleaks-reuse
on:
    pull_request:
    push:
    workflow_dispatch:
    schedule:
        - cron: "0 4 * * *" # run once a day at 4 AM
jobs:
    scan-reuse:
        uses: halt9k/shared-workflows/.github/workflows/scan.yml@main
        secrets: inherit
